version: "3.7"
services:
  test:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9229:9229" # Debugger
    volumes:
      - .:/usr/app
    stdin_open: true
    tty: true